"""Reservations, Scheduling, Availability, Waiting Lists, and Concurrency Domain for ForgeDesk."""

from forgedesk.reservations.availability import (
    calculate_concurrent_utilization,
    check_machine_availability,
    find_interval_conflicts,
    generate_timeline_slots,
    get_batch_machine_availability,
    get_historical_reservations_for_machine,
    validate_member_reservation_eligibility,
    validate_reservation_timing,
)
from forgedesk.reservations.handlers import (
    register_availability_routes,
    register_reservation_routes,
)
from forgedesk.reservations.recurrence import (
    MAX_RECURRENCE_COUNT,
    RecurrenceRuleError,
    format_recurrence_summary,
    generate_occurrence_datetimes,
    parse_recurrence_rule,
)
from forgedesk.reservations.service import (
    ACTIVE_RESERVATION_STATUSES,
    VALID_RESERVATION_STATUSES,
    ReservationConflictError,
    ReservationEligibilityError,
    ReservationNotFoundError,
    ReservationPermissionError,
    cancel_recurring_series,
    cancel_reservation,
    check_in_reservation,
    check_out_reservation,
    create_recurring_reservations,
    create_reservation,
    estimate_reservation_charge,
    format_conflict_explanation,
    get_recurring_series,
    get_reservation_by_id,
    list_reservations,
    mark_reservation_late,
    mark_reservation_no_show,
    process_overdue_reservations,
    update_reservation,
)
from forgedesk.reservations.waiting_list import (
    VALID_WAITING_STATUSES,
    WaitingListEligibilityError,
    WaitingListError,
    WaitingListNotFoundError,
    WaitingListPermissionError,
    cancel_waiting_list_entry,
    create_waiting_list_entry,
    evaluate_entry_eligibility,
    get_waiting_list_entry_by_id,
    list_waiting_list_entries,
    promote_first_eligible_waiting_entry,
    promote_waiting_list_entry_by_id,
)

__all__ = [
    # Availability & Conflicts
    "calculate_concurrent_utilization",
    "check_machine_availability",
    "find_interval_conflicts",
    "generate_timeline_slots",
    "get_batch_machine_availability",
    "get_historical_reservations_for_machine",
    "validate_member_reservation_eligibility",
    "validate_reservation_timing",
    # Recurrence Engine
    "MAX_RECURRENCE_COUNT",
    "RecurrenceRuleError",
    "parse_recurrence_rule",
    "generate_occurrence_datetimes",
    "format_recurrence_summary",
    # Service CRUD & Lifecycle
    "ACTIVE_RESERVATION_STATUSES",
    "VALID_RESERVATION_STATUSES",
    "ReservationConflictError",
    "ReservationEligibilityError",
    "ReservationNotFoundError",
    "ReservationPermissionError",
    "create_reservation",
    "create_recurring_reservations",
    "get_reservation_by_id",
    "get_recurring_series",
    "list_reservations",
    "update_reservation",
    "cancel_reservation",
    "cancel_recurring_series",
    "check_in_reservation",
    "check_out_reservation",
    "mark_reservation_late",
    "mark_reservation_no_show",
    "process_overdue_reservations",
    "estimate_reservation_charge",
    "format_conflict_explanation",
    # Waiting List & Promotion
    "VALID_WAITING_STATUSES",
    "WaitingListError",
    "WaitingListEligibilityError",
    "WaitingListNotFoundError",
    "WaitingListPermissionError",
    "create_waiting_list_entry",
    "get_waiting_list_entry_by_id",
    "list_waiting_list_entries",
    "cancel_waiting_list_entry",
    "evaluate_entry_eligibility",
    "promote_first_eligible_waiting_entry",
    "promote_waiting_list_entry_by_id",
    # Route Handlers
    "register_reservation_routes",
    "register_availability_routes",
]
