// Paper portfolios: identity, per-currency cash ledger, net spot positions,
// order records and the enduring blotter. Pure domain logic with injectable
// storage and clock so the browser app and the deterministic node checks share
// exactly one behaviour.
//
// Persistence is a single JSON document (schema versioned) held by the caller's
// storage — localStorage in the browser, a fake in tests. On first launch there
// is no stored document, so no portfolios exist and the trading record is empty.
//
// The blotter is append-only: a fill record is frozen when written and no later
// price update, order event or reload ever rewrites an earlier execution.

import { CURRENCIES, PAIRS, pairOf, money } from "./units.js";

export const ORDER_STATUS = ["pending", "filled", "cancelled", "rejected"];
export const ORDER_SIDES = ["buy", "sell"];
export const ORDER_TYPES = ["market", "limit"];

export const PORTFOLIO_SCHEMA_VERSION = 3;
export const DEFAULT_STORAGE_KEY = "fx-terminal.portfolios.v1";

function emptyCash() {
  return Object.fromEntries(CURRENCIES.map((c) => [c, 0]));
}

// v1 (S02) documents predate options: add the option book fields in place so
// existing paper portfolios, orders and blotters survive the upgrade.
// v2 (S03) documents predate the equity curve: add the equity sample history.
function migrate(state) {
  if (state.version === 1) {
    for (const pf of Object.values(state.portfolios ?? {})) {
      pf.optionOrders = pf.optionOrders ?? [];
      pf.optionLots = pf.optionLots ?? [];
      pf.seq = { order: 0, fill: 0, optionOrder: 0, lot: 0, ...(pf.seq ?? {}) };
    }
    state.version = 2;
  }
  if (state.version === 2) {
    for (const pf of Object.values(state.portfolios ?? {})) {
      pf.equityHistory = pf.equityHistory ?? [];
    }
    state.version = 3;
  }
  return state;
}

export function createPortfolio({ id, name, reportingCurrency, startingEquityAmount, createdAtMs }) {
  if (!name || typeof name !== "string") throw new Error("portfolio name is required");
  if (!CURRENCIES.includes(reportingCurrency)) {
    throw new Error(`unsupported reporting currency: ${reportingCurrency}`);
  }
  if (!(typeof startingEquityAmount === "number" && Number.isFinite(startingEquityAmount)
    && startingEquityAmount > 0)) {
    throw new Error(`starting equity must be a positive number, got ${startingEquityAmount}`);
  }
  const cash = emptyCash();
  cash[reportingCurrency] = startingEquityAmount;
  return {
    id,
    name,
    reportingCurrency,
    startingEquity: money(startingEquityAmount, reportingCurrency),
    createdAtMs,
    cash,
    positions: {},  // symbol -> { qtyBase (signed), avgPrice, realizedPnlQuote }
    orders: [],     // every spot order ever placed, incl. cancelled/rejected (history)
    optionOrders: [], // every option order ever placed, incl. rejected (history)
    optionLots: [],   // option lots: open, closed and expired
    blotter: [],    // append-only frozen fill records (spot and option)
    equityHistory: [], // equity samples { t, amount, currency } in reporting ccy
    seq: { order: 0, fill: 0, optionOrder: 0, lot: 0 },
  };
}

// Apply a fill's cash and position effects. Returns the realized P&L in the
// pair's quote currency generated by this fill (0 when it only opens/adds).
export function applyFillToPortfolio(pf, { symbol, side, qtyAmount, price }) {
  const pair = pairOf(symbol);
  const signedQty = side === "buy" ? qtyAmount : -qtyAmount;
  pf.cash[pair.base] += signedQty;
  pf.cash[pair.quote] -= signedQty * price;

  const pos = pf.positions[symbol] ?? { qtyBase: 0, avgPrice: 0, realizedPnlQuote: 0 };
  let realized = 0;

  if (pos.qtyBase === 0 || Math.sign(pos.qtyBase) === Math.sign(signedQty)) {
    // Opening or adding: weighted average open price.
    const newQty = pos.qtyBase + signedQty;
    pos.avgPrice = newQty === 0 ? 0
      : (pos.qtyBase * pos.avgPrice + signedQty * price) / newQty;
    pos.qtyBase = newQty;
  } else {
    // Reducing or flipping: the closing part realizes P&L against avgPrice.
    const closingQty = Math.min(Math.abs(pos.qtyBase), Math.abs(signedQty));
    realized = closingQty * (price - pos.avgPrice) * Math.sign(pos.qtyBase);
    pos.realizedPnlQuote += realized;
    const remainder = pos.qtyBase + signedQty;
    if (remainder === 0) {
      pos.qtyBase = 0;
      pos.avgPrice = 0;
    } else if (Math.sign(remainder) === Math.sign(signedQty)) {
      // Flipped through flat: the remainder opens at this fill's price.
      pos.qtyBase = remainder;
      pos.avgPrice = price;
    } else {
      pos.qtyBase = remainder;
    }
  }

  if (pos.qtyBase === 0 && pos.realizedPnlQuote === 0) {
    delete pf.positions[symbol];
  } else {
    pf.positions[symbol] = pos;
  }
  return realized;
}

export class PortfolioStore {
  // storage: { getItem(k), setItem(k, v) } or null for a pure in-memory store.
  constructor({ storage = null, storageKey = DEFAULT_STORAGE_KEY, now = () => Date.now() } = {}) {
    this.storage = storage;
    this.storageKey = storageKey;
    this.now = now;
    this._state = { version: PORTFOLIO_SCHEMA_VERSION, activeId: null, portfolioSeq: 0, portfolios: {} };
    this._load();
  }

  _load() {
    if (!this.storage) return;
    let raw = null;
    try { raw = this.storage.getItem(this.storageKey); } catch { raw = null; }
    if (!raw) return; // first launch: trading record stays empty
    try {
      const parsed = JSON.parse(raw);
      if (parsed && parsed.portfolios && parsed.version >= 1
        && parsed.version <= PORTFOLIO_SCHEMA_VERSION) {
        const originalVersion = parsed.version;
        this._state = migrate(parsed);
        if (this._state.version !== originalVersion) this._save();
      }
      // An unknown/corrupt document is ignored rather than crashing the
      // terminal; the stored bytes are left untouched.
    } catch { /* corrupt JSON: start empty, leave storage untouched */ }
  }

  _save() {
    if (!this.storage) return;
    this.storage.setItem(this.storageKey, JSON.stringify(this._state));
  }

  list() {
    return Object.values(this._state.portfolios)
      .map((p) => ({
        id: p.id, name: p.name, reportingCurrency: p.reportingCurrency,
        startingEquity: p.startingEquity, createdAtMs: p.createdAtMs,
      }))
      .sort((a, b) => a.createdAtMs - b.createdAtMs);
  }

  get(id) { return this._state.portfolios[id] ?? null; }
  active() { return this._state.activeId ? this.get(this._state.activeId) : null; }

  create({ name, startingEquityAmount, reportingCurrency }) {
    const id = `pf-${++this._state.portfolioSeq}`;
    const pf = createPortfolio({
      id, name, reportingCurrency, startingEquityAmount, createdAtMs: this.now(),
    });
    this._state.portfolios[id] = pf;
    this._state.activeId = id;
    this._save();
    return pf;
  }

  select(id) {
    if (!this.get(id)) throw new Error(`unknown portfolio: ${id}`);
    this._state.activeId = id;
    this._save();
  }

  // Mutate a portfolio and persist atomically afterwards.
  update(id, fn) {
    const pf = this.get(id);
    if (!pf) throw new Error(`unknown portfolio: ${id}`);
    const result = fn(pf);
    this._save();
    return result;
  }

  allPortfolios() { return Object.values(this._state.portfolios); }
}
